apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-neo4j-data-0
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  local:
    path: /data/neo4j-data-0   # must exist on the node
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - unicorn.local       # replace with your node name
  persistentVolumeReclaimPolicy: Retain

