apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-neo4j
  namespace: neo4j
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/neo4j
  storageClassName: ""
