#2026-07-03
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-data-pvc
  namespace: neo4j
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage
  volumeName: pv-neo4j-data   # explicitly bind to this PV
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-backup-pvc
  namespace: neo4j
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage
  volumeName: pv-neo4j-backup # explicitly bind to this PV

