neo4j:
  edition: community
  name: my-neo4j

volumes:
  data:
    mode: dynamic
    dynamic:
      storageClassName: local-path
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi

env:
  NEO4J_AUTH: neo4j/7D7D68D

config:
  server.memory.heap.initial_size: 512m
  server.memory.heap.max_size: 512m
  server.memory.pagecache.size: 512m

securityContext:
  fsGroup: 7474

