#!/bin/bash 
#written by Bharath Jeeva on 2026-02-28

#install updates and certs
apt-get update
apt-get install -y apt-transport-https ca-certificates curl gpg

#install openssh-server
apt install openssh-server -y

#step: install basic tools like traceroute, at, nmap, iotop, htop, vim, netstat
apt install traceroute at nmap iotop htop gzip locate vim  -y

#install docker, kind
apt install docker.io kind

#install Git
apt install git -y

#git auth

ls -al ~/.ssh

#set -x # start debugging
#check the folder for exiting key before creating key 
KEY_PATH="$HOME/.ssh/ed25519"
if [ -f "$KEY_PATH" ]; then
	echo "key already exist in $(whoami)@$(hostname)"
else 
	echo "generating new key on $(date)"
	ssh-keygen -t ed25519 -f "$KEY_PATH" -N "" -C "bharath814@gmail.com" -q
	echo "new key generated, check in "$KEY_PATH" location"
fi
chmod 600 "$KEY_PATH"
chmod 600 "$KEY_PATH.pub"

git config --global user.email "bharath814@gmail.com"
git config --global user.name "Bharath Jeeva"
ssh -T git@github.com
git clone https://github.com/bharathjeevanandham/bharathk8s.git
git status

#install kubectl
apt-get install kubectl -y

#install 
#apt install 

#install helm
apt install helm -y

#download and install chrome
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
chmod +x ./google-chrome-stable_current_amd.deb
apt install ./google-chrome-stable_current_amd.deb

#install terrraform
sudo apt-get update && sudo apt-get install -y gnupg software-properties-common
wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null
gpg --no-default-keyring --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg --fingerprint
echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(grep -oP '(?<=UBUNTU_CODENAME=).*' /etc/os-release || lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
apt update
apt install terraform
if [ $? = 0 ]; then
	echo "terraform installed successfully"
fi
