apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: monitor-binding
  namespace: prod
subjects:
  - kind: ServiceAccount
    name: monitor-sa
    namespace: prod
roleRef:
  kind: Role
  name: pod-monitor-role
  apiGroup: rbac.authorization.k8s.io
