apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-monitor-role
  namespace: prod
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
