---
apiVersion: v1
kind: Pod
metadata:
  name: pod-ssd
spec:
  containers:
    - name: pod-with-ssd
      image: busybox
      command: ["sleep", "3600"]
      volumeMounts:
        - mountPath: /data
          name: my-storage
  volumes:
    - name: my-storage
      persistentVolumeClaim:
        claimName: ssd-pvc
