---
apiVersion: v1
kind: Pod
metadata:
  name: bm-webapp-1
spec:
  nodeSelector:
    hardisk: ssd
  containers:
  - name: nginx
    image: nginx:latest
    ports:
      - containerPort: 80
    envFrom:
      - configMapRef:
           name: bm-app-config
