---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: lab-pv1
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /lab-volume/my-pv1
    type: Directory
