apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-backups-pvc
  namespace: grafana
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi # Adjust size based on your retention needs
