apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-pv
  namespace: default
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/harbor
  storageClassName: ""
