---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-general-rwm-2
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
