apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-pv-trivy
  namespace: default
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/harbor/trivy
  storageClassName: ""
