apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-prometheus-alertmanager
  namespace: prometheus
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /alertmanager
  storageClassName: ""
