apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-neo4j
  namespace: neo4j
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""  
  volumeName: pv-neo4j-backup
  resources:
    requests:
      storage: 3Gi
